remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme
title: Barabasz Silva Rerum
description: A bunch of more or less useful things
show_downloads: false
google_analytics: G-NQVS26YLP3
